branch-defaults:
  master:
    environment: AI-Project-Environment
  webServer:
    environment: AI-Project-Environment
deploy:
  artifact: docker-compose.yml
environment-defaults:
  AI-Project-Environment:
    branch: null
    repository: null
global:
  application_name: AI-Project
  default_ec2_keyname: ai-project-ssh
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
